### ISSUE TITLE
Change Datalabels for individual series, advanced mode

### ISSUE THREAD

**Issue by phoenixrip** [highcharts/highcharts-editor#118] opened 2017-01-11 16:21 UTC
Not sure if this is caused by #95 and therefore already being addressed, but changing datalabels for  individual series in a chart seems to not work.

Each individual series>datalabels entry seems to apply only to the second series, or, will only control all series.

Placing one series Datalabels below and another above is impossible, as the last change you made will apply to all series, regardless of if you applied it only to series4 in the advanced editor.

**Comment by cvasseng** [comment] 2017-01-12 07:13
Yeah, this is related to #95. 

Still no ETA on it, but it's among the two highest prioritized tasks right now (along with the data import revamp).

**Comment by cvasseng** [comment] 2017-01-12 07:13
Duplicate of #95

**Closed** 2017-07-20 11:19 UTC
Labels: bug, duplicate
